//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticeWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActaConformidad
    {
        public int codActa { get; set; }
        public Nullable<int> codGrupoPago { get; set; }
        public Nullable<int> codString { get; set; }
        public Nullable<int> codTipoDocumento { get; set; }
        public string condicionPago { get; set; }
        public string idAnticipo { get; set; }
        public Nullable<decimal> montoTotal { get; set; }
        public Nullable<decimal> impRenta { get; set; }
        public Nullable<decimal> subTotal { get; set; }
        public Nullable<int> codProveedor { get; set; }
        public string nroRuc { get; set; }
        public string nroOrdenCompra { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string solicitante { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> usuarioCreacion { get; set; }
    }
}
