//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticeWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCurso
    {
        public int codAsignacionCurso { get; set; }
        public string codCurso { get; set; }
        public Nullable<int> codDocente { get; set; }
        public Nullable<int> codLineaNegocio { get; set; }
        public Nullable<int> codModalidad { get; set; }
        public string codPeriodo { get; set; }
        public string asignado { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioModificacion { get; set; }
        public string docDiseño { get; set; }
    }
}
