//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticeWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public string codCurso { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<int> codDireccionCurso { get; set; }
        public Nullable<int> codLineaNegocii { get; set; }
        public string esBlended { get; set; }
        public string esBlenderizable { get; set; }
        public Nullable<decimal> horas { get; set; }
        public Nullable<int> codPersona { get; set; }
    }
}
