//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticeWS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ticeEntities3 : DbContext
    {
        public ticeEntities3()
            : base("name=ticeEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsignacionCurso> AsignacionCurso { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
    
        public virtual ObjectResult<SP_ACTIVIDAD_RETRIEVE_BY_CURSO_Result> SP_ACTIVIDAD_RETRIEVE_BY_CURSO(string periodo, string estado)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTIVIDAD_RETRIEVE_BY_CURSO_Result>("SP_ACTIVIDAD_RETRIEVE_BY_CURSO", periodoParameter, estadoParameter);
        }
    
        public virtual int SP_ACTIVIDAD_CREATE(Nullable<int> codigoCurso, Nullable<int> codigoModalidad, Nullable<int> codigoPeriodo, Nullable<int> codigoTipoCurso, string titulo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigoSesion, Nullable<int> codigoEstado, string descripcion, string usuarioCreacion)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoModalidadParameter = codigoModalidad.HasValue ?
                new ObjectParameter("codigoModalidad", codigoModalidad) :
                new ObjectParameter("codigoModalidad", typeof(int));
    
            var codigoPeriodoParameter = codigoPeriodo.HasValue ?
                new ObjectParameter("codigoPeriodo", codigoPeriodo) :
                new ObjectParameter("codigoPeriodo", typeof(int));
    
            var codigoTipoCursoParameter = codigoTipoCurso.HasValue ?
                new ObjectParameter("codigoTipoCurso", codigoTipoCurso) :
                new ObjectParameter("codigoTipoCurso", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var codigoSesionParameter = codigoSesion.HasValue ?
                new ObjectParameter("codigoSesion", codigoSesion) :
                new ObjectParameter("codigoSesion", typeof(int));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("codigoEstado", codigoEstado) :
                new ObjectParameter("codigoEstado", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVIDAD_CREATE", codigoCursoParameter, codigoModalidadParameter, codigoPeriodoParameter, codigoTipoCursoParameter, tituloParameter, fechaInicioParameter, fechaFinParameter, codigoSesionParameter, codigoEstadoParameter, descripcionParameter, usuarioCreacionParameter);
        }
    
        public virtual int SP_ACTIVIDAD_DELETE(Nullable<int> codigoActividad)
        {
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVIDAD_DELETE", codigoActividadParameter);
        }
    
        public virtual int SP_ACTIVIDAD_UPDATE(Nullable<int> codigoActividad, Nullable<int> codigoCurso, Nullable<int> codigoModalidad, Nullable<int> codigoPeriodo, Nullable<int> codigoTipoCurso, string titulo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigoSesion, Nullable<int> codigoEstado, string descripcion, string usuarioModificacion)
        {
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoModalidadParameter = codigoModalidad.HasValue ?
                new ObjectParameter("codigoModalidad", codigoModalidad) :
                new ObjectParameter("codigoModalidad", typeof(int));
    
            var codigoPeriodoParameter = codigoPeriodo.HasValue ?
                new ObjectParameter("codigoPeriodo", codigoPeriodo) :
                new ObjectParameter("codigoPeriodo", typeof(int));
    
            var codigoTipoCursoParameter = codigoTipoCurso.HasValue ?
                new ObjectParameter("codigoTipoCurso", codigoTipoCurso) :
                new ObjectParameter("codigoTipoCurso", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var codigoSesionParameter = codigoSesion.HasValue ?
                new ObjectParameter("codigoSesion", codigoSesion) :
                new ObjectParameter("codigoSesion", typeof(int));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("codigoEstado", codigoEstado) :
                new ObjectParameter("codigoEstado", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVIDAD_UPDATE", codigoActividadParameter, codigoCursoParameter, codigoModalidadParameter, codigoPeriodoParameter, codigoTipoCursoParameter, tituloParameter, fechaInicioParameter, fechaFinParameter, codigoSesionParameter, codigoEstadoParameter, descripcionParameter, usuarioModificacionParameter);
        }
    
        public virtual int SP_TAREA_CREATE(Nullable<int> codigoCurso, Nullable<int> codigoActividad, string titulo, Nullable<int> codigoPrioridad, string estado, Nullable<int> porcentajeCompletado, Nullable<int> codigoRecurso, string descripcion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string usuarioCreacion)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var codigoPrioridadParameter = codigoPrioridad.HasValue ?
                new ObjectParameter("codigoPrioridad", codigoPrioridad) :
                new ObjectParameter("codigoPrioridad", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var porcentajeCompletadoParameter = porcentajeCompletado.HasValue ?
                new ObjectParameter("porcentajeCompletado", porcentajeCompletado) :
                new ObjectParameter("porcentajeCompletado", typeof(int));
    
            var codigoRecursoParameter = codigoRecurso.HasValue ?
                new ObjectParameter("codigoRecurso", codigoRecurso) :
                new ObjectParameter("codigoRecurso", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAREA_CREATE", codigoCursoParameter, codigoActividadParameter, tituloParameter, codigoPrioridadParameter, estadoParameter, porcentajeCompletadoParameter, codigoRecursoParameter, descripcionParameter, fechaInicioParameter, fechaFinParameter, usuarioCreacionParameter);
        }
    
        public virtual int SP_TAREA_DELETE(Nullable<int> codigoTarea)
        {
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAREA_DELETE", codigoTareaParameter);
        }
    
        public virtual ObjectResult<SP_TAREA_RETRIEVE_BY_ACTIVIDAD_Result> SP_TAREA_RETRIEVE_BY_ACTIVIDAD(Nullable<int> codigoActividad)
        {
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TAREA_RETRIEVE_BY_ACTIVIDAD_Result>("SP_TAREA_RETRIEVE_BY_ACTIVIDAD", codigoActividadParameter);
        }
    
        public virtual int SP_TAREA_UPDATE(Nullable<int> codigoTarea, Nullable<int> codigoCurso, Nullable<int> codigoActividad, string titulo, Nullable<int> codigoPrioridad, string estado, Nullable<int> porcentajeCompletado, Nullable<int> codigoRecurso, string descripcion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string usuarioModificacion)
        {
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var codigoPrioridadParameter = codigoPrioridad.HasValue ?
                new ObjectParameter("codigoPrioridad", codigoPrioridad) :
                new ObjectParameter("codigoPrioridad", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var porcentajeCompletadoParameter = porcentajeCompletado.HasValue ?
                new ObjectParameter("porcentajeCompletado", porcentajeCompletado) :
                new ObjectParameter("porcentajeCompletado", typeof(int));
    
            var codigoRecursoParameter = codigoRecurso.HasValue ?
                new ObjectParameter("codigoRecurso", codigoRecurso) :
                new ObjectParameter("codigoRecurso", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAREA_UPDATE", codigoTareaParameter, codigoCursoParameter, codigoActividadParameter, tituloParameter, codigoPrioridadParameter, estadoParameter, porcentajeCompletadoParameter, codigoRecursoParameter, descripcionParameter, fechaInicioParameter, fechaFinParameter, usuarioModificacionParameter);
        }
    
        public virtual ObjectResult<SP_DOCUMENTO_RETRIEVE_BY_TAREA_Result> SP_DOCUMENTO_RETRIEVE_BY_TAREA(Nullable<int> codigoTarea)
        {
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOCUMENTO_RETRIEVE_BY_TAREA_Result>("SP_DOCUMENTO_RETRIEVE_BY_TAREA", codigoTareaParameter);
        }
    
        public virtual ObjectResult<SP_CURSO_RETRIEVE_Result> SP_CURSO_RETRIEVE(Nullable<int> codigoCurso)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CURSO_RETRIEVE_Result>("SP_CURSO_RETRIEVE", codigoCursoParameter);
        }
    
        public virtual int SP_DOCUMENTO_CREATE(Nullable<int> codigoCurso, Nullable<int> codigoActividad, Nullable<int> codigoTarea, string titulo, string autor, Nullable<int> codigoTipoDocumento, string descripcion, string rutaDocumento, string estado, string usuarioCreacion)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var codigoTipoDocumentoParameter = codigoTipoDocumento.HasValue ?
                new ObjectParameter("codigoTipoDocumento", codigoTipoDocumento) :
                new ObjectParameter("codigoTipoDocumento", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var rutaDocumentoParameter = rutaDocumento != null ?
                new ObjectParameter("rutaDocumento", rutaDocumento) :
                new ObjectParameter("rutaDocumento", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DOCUMENTO_CREATE", codigoCursoParameter, codigoActividadParameter, codigoTareaParameter, tituloParameter, autorParameter, codigoTipoDocumentoParameter, descripcionParameter, rutaDocumentoParameter, estadoParameter, usuarioCreacionParameter);
        }
    
        public virtual ObjectResult<SP_ACTIVIDAD_RETRIEVE_BY_CURSO2_Result> SP_ACTIVIDAD_RETRIEVE_BY_CURSO2(Nullable<int> codigoCurso)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTIVIDAD_RETRIEVE_BY_CURSO2_Result>("SP_ACTIVIDAD_RETRIEVE_BY_CURSO2", codigoCursoParameter);
        }
    
        public virtual ObjectResult<SP_ACTIVIDAD_RETRIEVE_Result> SP_ACTIVIDAD_RETRIEVE(Nullable<int> codigoActividad)
        {
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTIVIDAD_RETRIEVE_Result>("SP_ACTIVIDAD_RETRIEVE", codigoActividadParameter);
        }
    
        public virtual ObjectResult<SP_TAREA_RETRIEVE_Result> SP_TAREA_RETRIEVE(Nullable<int> codigoTarea)
        {
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TAREA_RETRIEVE_Result>("SP_TAREA_RETRIEVE", codigoTareaParameter);
        }
    
        public virtual ObjectResult<SP_DOCUMENTO_RETRIEVE_Result> SP_DOCUMENTO_RETRIEVE(Nullable<int> codigoDocumento)
        {
            var codigoDocumentoParameter = codigoDocumento.HasValue ?
                new ObjectParameter("codigoDocumento", codigoDocumento) :
                new ObjectParameter("codigoDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOCUMENTO_RETRIEVE_Result>("SP_DOCUMENTO_RETRIEVE", codigoDocumentoParameter);
        }
    
        public virtual int SP_DOCUMENTO_DELETE(Nullable<int> codigoDocumento)
        {
            var codigoDocumentoParameter = codigoDocumento.HasValue ?
                new ObjectParameter("codigoDocumento", codigoDocumento) :
                new ObjectParameter("codigoDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DOCUMENTO_DELETE", codigoDocumentoParameter);
        }
    
        public virtual int SP_DOCUMENTO_UPDATE(Nullable<int> codigoDocumento, Nullable<int> codigoCurso, Nullable<int> codigoActividad, Nullable<int> codigoTarea, string titulo, string autor, Nullable<int> codigoTipoDocumento, string descripcion, string rutaDocumento, string estado, string usuarioModificacion)
        {
            var codigoDocumentoParameter = codigoDocumento.HasValue ?
                new ObjectParameter("codigoDocumento", codigoDocumento) :
                new ObjectParameter("codigoDocumento", typeof(int));
    
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var codigoTipoDocumentoParameter = codigoTipoDocumento.HasValue ?
                new ObjectParameter("codigoTipoDocumento", codigoTipoDocumento) :
                new ObjectParameter("codigoTipoDocumento", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var rutaDocumentoParameter = rutaDocumento != null ?
                new ObjectParameter("rutaDocumento", rutaDocumento) :
                new ObjectParameter("rutaDocumento", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DOCUMENTO_UPDATE", codigoDocumentoParameter, codigoCursoParameter, codigoActividadParameter, codigoTareaParameter, tituloParameter, autorParameter, codigoTipoDocumentoParameter, descripcionParameter, rutaDocumentoParameter, estadoParameter, usuarioModificacionParameter);
        }
    
        public virtual int SP_CURSO_UPDATE(Nullable<int> codigoCurso, string nombreCurso, string estado, string observaciones, string usuarioModificacion)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var nombreCursoParameter = nombreCurso != null ?
                new ObjectParameter("nombreCurso", nombreCurso) :
                new ObjectParameter("nombreCurso", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CURSO_UPDATE", codigoCursoParameter, nombreCursoParameter, estadoParameter, observacionesParameter, usuarioModificacionParameter);
        }
    
        public virtual ObjectResult<SP_CAPACITACION_RETRIEVE_BY_FILTER_Result> SP_CAPACITACION_RETRIEVE_BY_FILTER(Nullable<int> codigoTaller, Nullable<int> codigoPeriodo, string nomCapacitacion)
        {
            var codigoTallerParameter = codigoTaller.HasValue ?
                new ObjectParameter("codigoTaller", codigoTaller) :
                new ObjectParameter("codigoTaller", typeof(int));
    
            var codigoPeriodoParameter = codigoPeriodo.HasValue ?
                new ObjectParameter("codigoPeriodo", codigoPeriodo) :
                new ObjectParameter("codigoPeriodo", typeof(int));
    
            var nomCapacitacionParameter = nomCapacitacion != null ?
                new ObjectParameter("nomCapacitacion", nomCapacitacion) :
                new ObjectParameter("nomCapacitacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CAPACITACION_RETRIEVE_BY_FILTER_Result>("SP_CAPACITACION_RETRIEVE_BY_FILTER", codigoTallerParameter, codigoPeriodoParameter, nomCapacitacionParameter);
        }
    
        public virtual int SP_CAPACITACION_CREATE(string nombre, Nullable<bool> certificado, Nullable<int> codigoPerido, string descripcion, string correoContacto, Nullable<bool> enviarNotificacion, Nullable<int> periodicidadEnvio, Nullable<System.DateTime> fechaInicio, Nullable<bool> capacitacionActiva, Nullable<int> codigoTaller, Nullable<System.DateTime> fechaCreacion, Nullable<System.DateTime> fechaModificacióm, string usuarioCreacion, string usuarioModificacion, string lugar, Nullable<System.DateTime> fechaInicioEnvio, Nullable<System.DateTime> fechaCapacitacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var certificadoParameter = certificado.HasValue ?
                new ObjectParameter("certificado", certificado) :
                new ObjectParameter("certificado", typeof(bool));
    
            var codigoPeridoParameter = codigoPerido.HasValue ?
                new ObjectParameter("codigoPerido", codigoPerido) :
                new ObjectParameter("codigoPerido", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var correoContactoParameter = correoContacto != null ?
                new ObjectParameter("correoContacto", correoContacto) :
                new ObjectParameter("correoContacto", typeof(string));
    
            var enviarNotificacionParameter = enviarNotificacion.HasValue ?
                new ObjectParameter("enviarNotificacion", enviarNotificacion) :
                new ObjectParameter("enviarNotificacion", typeof(bool));
    
            var periodicidadEnvioParameter = periodicidadEnvio.HasValue ?
                new ObjectParameter("periodicidadEnvio", periodicidadEnvio) :
                new ObjectParameter("periodicidadEnvio", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var capacitacionActivaParameter = capacitacionActiva.HasValue ?
                new ObjectParameter("capacitacionActiva", capacitacionActiva) :
                new ObjectParameter("capacitacionActiva", typeof(bool));
    
            var codigoTallerParameter = codigoTaller.HasValue ?
                new ObjectParameter("codigoTaller", codigoTaller) :
                new ObjectParameter("codigoTaller", typeof(int));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("fechaCreacion", fechaCreacion) :
                new ObjectParameter("fechaCreacion", typeof(System.DateTime));
    
            var fechaModificaciómParameter = fechaModificacióm.HasValue ?
                new ObjectParameter("fechaModificacióm", fechaModificacióm) :
                new ObjectParameter("fechaModificacióm", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("lugar", lugar) :
                new ObjectParameter("lugar", typeof(string));
    
            var fechaInicioEnvioParameter = fechaInicioEnvio.HasValue ?
                new ObjectParameter("fechaInicioEnvio", fechaInicioEnvio) :
                new ObjectParameter("fechaInicioEnvio", typeof(System.DateTime));
    
            var fechaCapacitacionParameter = fechaCapacitacion.HasValue ?
                new ObjectParameter("fechaCapacitacion", fechaCapacitacion) :
                new ObjectParameter("fechaCapacitacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPACITACION_CREATE", nombreParameter, certificadoParameter, codigoPeridoParameter, descripcionParameter, correoContactoParameter, enviarNotificacionParameter, periodicidadEnvioParameter, fechaInicioParameter, capacitacionActivaParameter, codigoTallerParameter, fechaCreacionParameter, fechaModificaciómParameter, usuarioCreacionParameter, usuarioModificacionParameter, lugarParameter, fechaInicioEnvioParameter, fechaCapacitacionParameter);
        }
    
        public virtual int SP_MATERIAL_CAPACITACION_CREATE(Nullable<int> codigoCapacitacion, string descripcion, string rutaDocumento)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var rutaDocumentoParameter = rutaDocumento != null ?
                new ObjectParameter("rutaDocumento", rutaDocumento) :
                new ObjectParameter("rutaDocumento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MATERIAL_CAPACITACION_CREATE", codigoCapacitacionParameter, descripcionParameter, rutaDocumentoParameter);
        }
    
        public virtual int SP_PARTICIPANTES_CAPACITACION_CREATE(Nullable<int> codigoDocente, Nullable<int> codigoCapacitacion, string nombreCompleto, Nullable<bool> enviarconvocatoria)
        {
            var codigoDocenteParameter = codigoDocente.HasValue ?
                new ObjectParameter("codigoDocente", codigoDocente) :
                new ObjectParameter("codigoDocente", typeof(int));
    
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("nombreCompleto", nombreCompleto) :
                new ObjectParameter("nombreCompleto", typeof(string));
    
            var enviarconvocatoriaParameter = enviarconvocatoria.HasValue ?
                new ObjectParameter("enviarconvocatoria", enviarconvocatoria) :
                new ObjectParameter("enviarconvocatoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PARTICIPANTES_CAPACITACION_CREATE", codigoDocenteParameter, codigoCapacitacionParameter, nombreCompletoParameter, enviarconvocatoriaParameter);
        }
    
        public virtual ObjectResult<SP_TALLER_RETRIEVE_Result> SP_TALLER_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TALLER_RETRIEVE_Result>("SP_TALLER_RETRIEVE");
        }
    
        public virtual ObjectResult<SP_MATERIAL_CAPACITACION_RETRIEVE_BY_CAPACITACION_Result> SP_MATERIAL_CAPACITACION_RETRIEVE_BY_CAPACITACION(Nullable<int> codigoCapacitacion)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MATERIAL_CAPACITACION_RETRIEVE_BY_CAPACITACION_Result>("SP_MATERIAL_CAPACITACION_RETRIEVE_BY_CAPACITACION", codigoCapacitacionParameter);
        }
    
        public virtual ObjectResult<SP_MATERIAL_RETRIEVE_Result> SP_MATERIAL_RETRIEVE(Nullable<int> codigoTaller)
        {
            var codigoTallerParameter = codigoTaller.HasValue ?
                new ObjectParameter("codigoTaller", codigoTaller) :
                new ObjectParameter("codigoTaller", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MATERIAL_RETRIEVE_Result>("SP_MATERIAL_RETRIEVE", codigoTallerParameter);
        }
    
        public virtual ObjectResult<SP_TALLER_RETRIEVE_BY_TALLER_Result> SP_TALLER_RETRIEVE_BY_TALLER(Nullable<int> codigoTaller)
        {
            var codigoTallerParameter = codigoTaller.HasValue ?
                new ObjectParameter("codigoTaller", codigoTaller) :
                new ObjectParameter("codigoTaller", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TALLER_RETRIEVE_BY_TALLER_Result>("SP_TALLER_RETRIEVE_BY_TALLER", codigoTallerParameter);
        }
    
        public virtual ObjectResult<SP_CAPACITACION_RETRIEVE_Result> SP_CAPACITACION_RETRIEVE(Nullable<int> codigoCapacitacion)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CAPACITACION_RETRIEVE_Result>("SP_CAPACITACION_RETRIEVE", codigoCapacitacionParameter);
        }
    
        public virtual ObjectResult<SP_PARTICIPANTES_CAPACITACION_RETRIEVE_BY_CAPACITACION_Result> SP_PARTICIPANTES_CAPACITACION_RETRIEVE_BY_CAPACITACION(Nullable<int> codigoCapacitacion)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PARTICIPANTES_CAPACITACION_RETRIEVE_BY_CAPACITACION_Result>("SP_PARTICIPANTES_CAPACITACION_RETRIEVE_BY_CAPACITACION", codigoCapacitacionParameter);
        }
    
        public virtual ObjectResult<SP_DOCENTE_RETRIEVE_Result> SP_DOCENTE_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOCENTE_RETRIEVE_Result>("SP_DOCENTE_RETRIEVE");
        }
    
        public virtual int SP_MATERIAL_CAPACITACION_DELETE(Nullable<int> codigoMaterial)
        {
            var codigoMaterialParameter = codigoMaterial.HasValue ?
                new ObjectParameter("codigoMaterial", codigoMaterial) :
                new ObjectParameter("codigoMaterial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MATERIAL_CAPACITACION_DELETE", codigoMaterialParameter);
        }
    
        public virtual int SP_PARTICIPANTES_CAPACITACION_DELETE(Nullable<int> codigoCapacitacion, Nullable<int> codigoDocente)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            var codigoDocenteParameter = codigoDocente.HasValue ?
                new ObjectParameter("codigoDocente", codigoDocente) :
                new ObjectParameter("codigoDocente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PARTICIPANTES_CAPACITACION_DELETE", codigoCapacitacionParameter, codigoDocenteParameter);
        }
    
        public virtual int SP_CAPACITACION_UPDATE(Nullable<int> codigoCapacitacion, string nombre, Nullable<bool> certificado, Nullable<int> codigoPerido, string descripcion, string correoContacto, Nullable<bool> enviarNotificacion, Nullable<int> periodicidadEnvio, Nullable<System.DateTime> fechaInicio, Nullable<bool> capacitacionActiva, Nullable<int> codigoTaller, Nullable<System.DateTime> fechaCreacion, Nullable<System.DateTime> fechaModificacióm, string usuarioCreacion, string usuarioModificacion, string lugar, Nullable<System.DateTime> fechaInicioEnvio, Nullable<System.DateTime> fechaCapacitacion)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var certificadoParameter = certificado.HasValue ?
                new ObjectParameter("certificado", certificado) :
                new ObjectParameter("certificado", typeof(bool));
    
            var codigoPeridoParameter = codigoPerido.HasValue ?
                new ObjectParameter("codigoPerido", codigoPerido) :
                new ObjectParameter("codigoPerido", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var correoContactoParameter = correoContacto != null ?
                new ObjectParameter("correoContacto", correoContacto) :
                new ObjectParameter("correoContacto", typeof(string));
    
            var enviarNotificacionParameter = enviarNotificacion.HasValue ?
                new ObjectParameter("enviarNotificacion", enviarNotificacion) :
                new ObjectParameter("enviarNotificacion", typeof(bool));
    
            var periodicidadEnvioParameter = periodicidadEnvio.HasValue ?
                new ObjectParameter("periodicidadEnvio", periodicidadEnvio) :
                new ObjectParameter("periodicidadEnvio", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var capacitacionActivaParameter = capacitacionActiva.HasValue ?
                new ObjectParameter("capacitacionActiva", capacitacionActiva) :
                new ObjectParameter("capacitacionActiva", typeof(bool));
    
            var codigoTallerParameter = codigoTaller.HasValue ?
                new ObjectParameter("codigoTaller", codigoTaller) :
                new ObjectParameter("codigoTaller", typeof(int));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("fechaCreacion", fechaCreacion) :
                new ObjectParameter("fechaCreacion", typeof(System.DateTime));
    
            var fechaModificaciómParameter = fechaModificacióm.HasValue ?
                new ObjectParameter("fechaModificacióm", fechaModificacióm) :
                new ObjectParameter("fechaModificacióm", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("lugar", lugar) :
                new ObjectParameter("lugar", typeof(string));
    
            var fechaInicioEnvioParameter = fechaInicioEnvio.HasValue ?
                new ObjectParameter("fechaInicioEnvio", fechaInicioEnvio) :
                new ObjectParameter("fechaInicioEnvio", typeof(System.DateTime));
    
            var fechaCapacitacionParameter = fechaCapacitacion.HasValue ?
                new ObjectParameter("fechaCapacitacion", fechaCapacitacion) :
                new ObjectParameter("fechaCapacitacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPACITACION_UPDATE", codigoCapacitacionParameter, nombreParameter, certificadoParameter, codigoPeridoParameter, descripcionParameter, correoContactoParameter, enviarNotificacionParameter, periodicidadEnvioParameter, fechaInicioParameter, capacitacionActivaParameter, codigoTallerParameter, fechaCreacionParameter, fechaModificaciómParameter, usuarioCreacionParameter, usuarioModificacionParameter, lugarParameter, fechaInicioEnvioParameter, fechaCapacitacionParameter);
        }
    
        public virtual ObjectResult<SP_ACTIVIDAD_RETRIEVE_BY_CURSO3_Result> SP_ACTIVIDAD_RETRIEVE_BY_CURSO3(Nullable<int> idperiodo, string estado)
        {
            var idperiodoParameter = idperiodo.HasValue ?
                new ObjectParameter("idperiodo", idperiodo) :
                new ObjectParameter("idperiodo", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTIVIDAD_RETRIEVE_BY_CURSO3_Result>("SP_ACTIVIDAD_RETRIEVE_BY_CURSO3", idperiodoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<SP_PERIODO_RETRIEVE_Result> SP_PERIODO_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PERIODO_RETRIEVE_Result>("SP_PERIODO_RETRIEVE");
        }
    }
}
