//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticeWS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ticeEntities3 : DbContext
    {
        public ticeEntities3()
            : base("name=ticeEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsignacionCurso> AsignacionCurso { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<Capacitacion> Capacitacion { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<Semana> Semana { get; set; }
        public virtual DbSet<TipoRecurso> TipoRecurso { get; set; }
        public virtual DbSet<Unidad> Unidad { get; set; }
        public virtual DbSet<Aula> Aula { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Modalidad> Modalidad { get; set; }
        public virtual DbSet<ActaConformidad> ActaConformidad { get; set; }
    
        public virtual ObjectResult<SP_ACTIVIDAD_RETRIEVE_BY_CURSO_Result> SP_ACTIVIDAD_RETRIEVE_BY_CURSO(string periodo, string estado)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTIVIDAD_RETRIEVE_BY_CURSO_Result>("SP_ACTIVIDAD_RETRIEVE_BY_CURSO", periodoParameter, estadoParameter);
        }
    
        public virtual int SP_ACTIVIDAD_CREATE(Nullable<int> codCurso, Nullable<int> codUnidad, Nullable<int> codSemana, string titulo, string estado, string descripcion, string usuarioCreacion)
        {
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            var codUnidadParameter = codUnidad.HasValue ?
                new ObjectParameter("codUnidad", codUnidad) :
                new ObjectParameter("codUnidad", typeof(int));
    
            var codSemanaParameter = codSemana.HasValue ?
                new ObjectParameter("codSemana", codSemana) :
                new ObjectParameter("codSemana", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVIDAD_CREATE", codCursoParameter, codUnidadParameter, codSemanaParameter, tituloParameter, estadoParameter, descripcionParameter, usuarioCreacionParameter);
        }
    
        public virtual int SP_ACTIVIDAD_DELETE(Nullable<int> codActividad)
        {
            var codActividadParameter = codActividad.HasValue ?
                new ObjectParameter("codActividad", codActividad) :
                new ObjectParameter("codActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVIDAD_DELETE", codActividadParameter);
        }
    
        public virtual int SP_ACTIVIDAD_UPDATE(Nullable<int> codActividad, Nullable<int> codCurso, Nullable<int> codUnidad, Nullable<int> codSemana, string titulo, Nullable<int> estado, string descripcion, string usuarioModificacion)
        {
            var codActividadParameter = codActividad.HasValue ?
                new ObjectParameter("codActividad", codActividad) :
                new ObjectParameter("codActividad", typeof(int));
    
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            var codUnidadParameter = codUnidad.HasValue ?
                new ObjectParameter("codUnidad", codUnidad) :
                new ObjectParameter("codUnidad", typeof(int));
    
            var codSemanaParameter = codSemana.HasValue ?
                new ObjectParameter("codSemana", codSemana) :
                new ObjectParameter("codSemana", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVIDAD_UPDATE", codActividadParameter, codCursoParameter, codUnidadParameter, codSemanaParameter, tituloParameter, estadoParameter, descripcionParameter, usuarioModificacionParameter);
        }
    
        public virtual int SP_TAREA_CREATE(Nullable<int> codCurso, Nullable<int> codActividad, string titulo, string estado, Nullable<int> porcentajeCompletado, Nullable<int> codTipoRecurso, Nullable<int> codRecurso, string descripcion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string usuarioCreacion)
        {
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            var codActividadParameter = codActividad.HasValue ?
                new ObjectParameter("codActividad", codActividad) :
                new ObjectParameter("codActividad", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var porcentajeCompletadoParameter = porcentajeCompletado.HasValue ?
                new ObjectParameter("porcentajeCompletado", porcentajeCompletado) :
                new ObjectParameter("porcentajeCompletado", typeof(int));
    
            var codTipoRecursoParameter = codTipoRecurso.HasValue ?
                new ObjectParameter("codTipoRecurso", codTipoRecurso) :
                new ObjectParameter("codTipoRecurso", typeof(int));
    
            var codRecursoParameter = codRecurso.HasValue ?
                new ObjectParameter("codRecurso", codRecurso) :
                new ObjectParameter("codRecurso", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAREA_CREATE", codCursoParameter, codActividadParameter, tituloParameter, estadoParameter, porcentajeCompletadoParameter, codTipoRecursoParameter, codRecursoParameter, descripcionParameter, fechaInicioParameter, fechaFinParameter, usuarioCreacionParameter);
        }
    
        public virtual int SP_TAREA_DELETE(Nullable<int> codTarea)
        {
            var codTareaParameter = codTarea.HasValue ?
                new ObjectParameter("codTarea", codTarea) :
                new ObjectParameter("codTarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAREA_DELETE", codTareaParameter);
        }
    
        public virtual ObjectResult<SP_TAREA_RETRIEVE_BY_ACTIVIDAD_Result> SP_TAREA_RETRIEVE_BY_ACTIVIDAD(Nullable<int> codActividad)
        {
            var codActividadParameter = codActividad.HasValue ?
                new ObjectParameter("codActividad", codActividad) :
                new ObjectParameter("codActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TAREA_RETRIEVE_BY_ACTIVIDAD_Result>("SP_TAREA_RETRIEVE_BY_ACTIVIDAD", codActividadParameter);
        }
    
        public virtual int SP_TAREA_UPDATE(Nullable<int> codTarea, Nullable<int> codCurso, Nullable<int> codActividad, string titulo, Nullable<int> codPrioridad, string estado, Nullable<int> porcentajeCompletado, Nullable<int> codRecurso, string descripcion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string usuarioModificacion)
        {
            var codTareaParameter = codTarea.HasValue ?
                new ObjectParameter("codTarea", codTarea) :
                new ObjectParameter("codTarea", typeof(int));
    
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            var codActividadParameter = codActividad.HasValue ?
                new ObjectParameter("codActividad", codActividad) :
                new ObjectParameter("codActividad", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var codPrioridadParameter = codPrioridad.HasValue ?
                new ObjectParameter("codPrioridad", codPrioridad) :
                new ObjectParameter("codPrioridad", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var porcentajeCompletadoParameter = porcentajeCompletado.HasValue ?
                new ObjectParameter("porcentajeCompletado", porcentajeCompletado) :
                new ObjectParameter("porcentajeCompletado", typeof(int));
    
            var codRecursoParameter = codRecurso.HasValue ?
                new ObjectParameter("codRecurso", codRecurso) :
                new ObjectParameter("codRecurso", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAREA_UPDATE", codTareaParameter, codCursoParameter, codActividadParameter, tituloParameter, codPrioridadParameter, estadoParameter, porcentajeCompletadoParameter, codRecursoParameter, descripcionParameter, fechaInicioParameter, fechaFinParameter, usuarioModificacionParameter);
        }
    
        public virtual ObjectResult<SP_DOCUMENTO_RETRIEVE_BY_TAREA_Result> SP_DOCUMENTO_RETRIEVE_BY_TAREA(Nullable<int> codigoTarea)
        {
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOCUMENTO_RETRIEVE_BY_TAREA_Result>("SP_DOCUMENTO_RETRIEVE_BY_TAREA", codigoTareaParameter);
        }
    
        public virtual ObjectResult<SP_CURSO_RETRIEVE_Result> SP_CURSO_RETRIEVE(Nullable<int> codigoCurso)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CURSO_RETRIEVE_Result>("SP_CURSO_RETRIEVE", codigoCursoParameter);
        }
    
        public virtual int SP_DOCUMENTO_CREATE(Nullable<int> codigoCurso, Nullable<int> codigoActividad, Nullable<int> codigoTarea, string titulo, string autor, Nullable<int> codigoTipoDocumento, string descripcion, string rutaDocumento, string estado, string usuarioCreacion)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var codigoTipoDocumentoParameter = codigoTipoDocumento.HasValue ?
                new ObjectParameter("codigoTipoDocumento", codigoTipoDocumento) :
                new ObjectParameter("codigoTipoDocumento", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var rutaDocumentoParameter = rutaDocumento != null ?
                new ObjectParameter("rutaDocumento", rutaDocumento) :
                new ObjectParameter("rutaDocumento", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DOCUMENTO_CREATE", codigoCursoParameter, codigoActividadParameter, codigoTareaParameter, tituloParameter, autorParameter, codigoTipoDocumentoParameter, descripcionParameter, rutaDocumentoParameter, estadoParameter, usuarioCreacionParameter);
        }
    
        public virtual ObjectResult<SP_ACTIVIDAD_RETRIEVE_BY_CURSO2_Result> SP_ACTIVIDAD_RETRIEVE_BY_CURSO2(Nullable<int> codCurso)
        {
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTIVIDAD_RETRIEVE_BY_CURSO2_Result>("SP_ACTIVIDAD_RETRIEVE_BY_CURSO2", codCursoParameter);
        }
    
        public virtual ObjectResult<SP_ACTIVIDAD_RETRIEVE_Result> SP_ACTIVIDAD_RETRIEVE(Nullable<int> codActividad)
        {
            var codActividadParameter = codActividad.HasValue ?
                new ObjectParameter("codActividad", codActividad) :
                new ObjectParameter("codActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTIVIDAD_RETRIEVE_Result>("SP_ACTIVIDAD_RETRIEVE", codActividadParameter);
        }
    
        public virtual ObjectResult<SP_TAREA_RETRIEVE_Result> SP_TAREA_RETRIEVE(Nullable<int> codTarea)
        {
            var codTareaParameter = codTarea.HasValue ?
                new ObjectParameter("codTarea", codTarea) :
                new ObjectParameter("codTarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TAREA_RETRIEVE_Result>("SP_TAREA_RETRIEVE", codTareaParameter);
        }
    
        public virtual ObjectResult<SP_DOCUMENTO_RETRIEVE_Result> SP_DOCUMENTO_RETRIEVE(Nullable<int> codigoDocumento)
        {
            var codigoDocumentoParameter = codigoDocumento.HasValue ?
                new ObjectParameter("codigoDocumento", codigoDocumento) :
                new ObjectParameter("codigoDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOCUMENTO_RETRIEVE_Result>("SP_DOCUMENTO_RETRIEVE", codigoDocumentoParameter);
        }
    
        public virtual int SP_DOCUMENTO_DELETE(Nullable<int> codigoDocumento)
        {
            var codigoDocumentoParameter = codigoDocumento.HasValue ?
                new ObjectParameter("codigoDocumento", codigoDocumento) :
                new ObjectParameter("codigoDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DOCUMENTO_DELETE", codigoDocumentoParameter);
        }
    
        public virtual int SP_DOCUMENTO_UPDATE(Nullable<int> codigoDocumento, Nullable<int> codigoCurso, Nullable<int> codigoActividad, Nullable<int> codigoTarea, string titulo, string autor, Nullable<int> codigoTipoDocumento, string descripcion, string rutaDocumento, string estado, string usuarioModificacion)
        {
            var codigoDocumentoParameter = codigoDocumento.HasValue ?
                new ObjectParameter("codigoDocumento", codigoDocumento) :
                new ObjectParameter("codigoDocumento", typeof(int));
    
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var codigoTipoDocumentoParameter = codigoTipoDocumento.HasValue ?
                new ObjectParameter("codigoTipoDocumento", codigoTipoDocumento) :
                new ObjectParameter("codigoTipoDocumento", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var rutaDocumentoParameter = rutaDocumento != null ?
                new ObjectParameter("rutaDocumento", rutaDocumento) :
                new ObjectParameter("rutaDocumento", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DOCUMENTO_UPDATE", codigoDocumentoParameter, codigoCursoParameter, codigoActividadParameter, codigoTareaParameter, tituloParameter, autorParameter, codigoTipoDocumentoParameter, descripcionParameter, rutaDocumentoParameter, estadoParameter, usuarioModificacionParameter);
        }
    
        public virtual int SP_CURSO_UPDATE(Nullable<int> codigoCurso, string nombreCurso, string estado, string observaciones, string usuarioModificacion)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var nombreCursoParameter = nombreCurso != null ?
                new ObjectParameter("nombreCurso", nombreCurso) :
                new ObjectParameter("nombreCurso", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CURSO_UPDATE", codigoCursoParameter, nombreCursoParameter, estadoParameter, observacionesParameter, usuarioModificacionParameter);
        }
    
        public virtual ObjectResult<SP_CAPACITACION_RETRIEVE_BY_FILTER_Result> SP_CAPACITACION_RETRIEVE_BY_FILTER(Nullable<int> codPeriodo, string nomCapacitacion)
        {
            var codPeriodoParameter = codPeriodo.HasValue ?
                new ObjectParameter("codPeriodo", codPeriodo) :
                new ObjectParameter("codPeriodo", typeof(int));
    
            var nomCapacitacionParameter = nomCapacitacion != null ?
                new ObjectParameter("nomCapacitacion", nomCapacitacion) :
                new ObjectParameter("nomCapacitacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CAPACITACION_RETRIEVE_BY_FILTER_Result>("SP_CAPACITACION_RETRIEVE_BY_FILTER", codPeriodoParameter, nomCapacitacionParameter);
        }
    
        public virtual int SP_CAPACITACION_CREATE(ObjectParameter codigoCapacitacion, string nombre, Nullable<int> codPerido, string descripcion, string correoContacto, Nullable<bool> enviarNotificacion, Nullable<int> periodicidadEnvio, Nullable<bool> capacitacionActiva, Nullable<System.DateTime> fechaCreacion, Nullable<System.DateTime> fechaModificacióm, string usuarioCreacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var codPeridoParameter = codPerido.HasValue ?
                new ObjectParameter("codPerido", codPerido) :
                new ObjectParameter("codPerido", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var correoContactoParameter = correoContacto != null ?
                new ObjectParameter("correoContacto", correoContacto) :
                new ObjectParameter("correoContacto", typeof(string));
    
            var enviarNotificacionParameter = enviarNotificacion.HasValue ?
                new ObjectParameter("enviarNotificacion", enviarNotificacion) :
                new ObjectParameter("enviarNotificacion", typeof(bool));
    
            var periodicidadEnvioParameter = periodicidadEnvio.HasValue ?
                new ObjectParameter("periodicidadEnvio", periodicidadEnvio) :
                new ObjectParameter("periodicidadEnvio", typeof(int));
    
            var capacitacionActivaParameter = capacitacionActiva.HasValue ?
                new ObjectParameter("capacitacionActiva", capacitacionActiva) :
                new ObjectParameter("capacitacionActiva", typeof(bool));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("fechaCreacion", fechaCreacion) :
                new ObjectParameter("fechaCreacion", typeof(System.DateTime));
    
            var fechaModificaciómParameter = fechaModificacióm.HasValue ?
                new ObjectParameter("fechaModificacióm", fechaModificacióm) :
                new ObjectParameter("fechaModificacióm", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPACITACION_CREATE", codigoCapacitacion, nombreParameter, codPeridoParameter, descripcionParameter, correoContactoParameter, enviarNotificacionParameter, periodicidadEnvioParameter, capacitacionActivaParameter, fechaCreacionParameter, fechaModificaciómParameter, usuarioCreacionParameter);
        }
    
        public virtual int SP_MATERIAL_CAPACITACION_CREATE(Nullable<int> codigoCapacitacion, string descripcion, string rutaDocumento)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var rutaDocumentoParameter = rutaDocumento != null ?
                new ObjectParameter("rutaDocumento", rutaDocumento) :
                new ObjectParameter("rutaDocumento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MATERIAL_CAPACITACION_CREATE", codigoCapacitacionParameter, descripcionParameter, rutaDocumentoParameter);
        }
    
        public virtual int SP_PARTICIPANTES_CAPACITACION_CREATE(Nullable<int> codigoDocente, Nullable<int> codigoCapacitacion, string nombreCompleto, Nullable<bool> enviarconvocatoria)
        {
            var codigoDocenteParameter = codigoDocente.HasValue ?
                new ObjectParameter("codigoDocente", codigoDocente) :
                new ObjectParameter("codigoDocente", typeof(int));
    
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("nombreCompleto", nombreCompleto) :
                new ObjectParameter("nombreCompleto", typeof(string));
    
            var enviarconvocatoriaParameter = enviarconvocatoria.HasValue ?
                new ObjectParameter("enviarconvocatoria", enviarconvocatoria) :
                new ObjectParameter("enviarconvocatoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PARTICIPANTES_CAPACITACION_CREATE", codigoDocenteParameter, codigoCapacitacionParameter, nombreCompletoParameter, enviarconvocatoriaParameter);
        }
    
        public virtual ObjectResult<SP_TALLER_RETRIEVE_Result> SP_TALLER_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TALLER_RETRIEVE_Result>("SP_TALLER_RETRIEVE");
        }
    
        public virtual ObjectResult<SP_MATERIAL_RETRIEVE_Result> SP_MATERIAL_RETRIEVE(Nullable<int> codigoTaller)
        {
            var codigoTallerParameter = codigoTaller.HasValue ?
                new ObjectParameter("codigoTaller", codigoTaller) :
                new ObjectParameter("codigoTaller", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MATERIAL_RETRIEVE_Result>("SP_MATERIAL_RETRIEVE", codigoTallerParameter);
        }
    
        public virtual ObjectResult<SP_TALLER_RETRIEVE_BY_TALLER_Result> SP_TALLER_RETRIEVE_BY_TALLER(Nullable<int> codigoTaller)
        {
            var codigoTallerParameter = codigoTaller.HasValue ?
                new ObjectParameter("codigoTaller", codigoTaller) :
                new ObjectParameter("codigoTaller", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TALLER_RETRIEVE_BY_TALLER_Result>("SP_TALLER_RETRIEVE_BY_TALLER", codigoTallerParameter);
        }
    
        public virtual ObjectResult<SP_CAPACITACION_RETRIEVE_Result> SP_CAPACITACION_RETRIEVE(Nullable<int> codCapacitacion)
        {
            var codCapacitacionParameter = codCapacitacion.HasValue ?
                new ObjectParameter("codCapacitacion", codCapacitacion) :
                new ObjectParameter("codCapacitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CAPACITACION_RETRIEVE_Result>("SP_CAPACITACION_RETRIEVE", codCapacitacionParameter);
        }
    
        public virtual ObjectResult<SP_DOCENTE_RETRIEVE_Result> SP_DOCENTE_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOCENTE_RETRIEVE_Result>("SP_DOCENTE_RETRIEVE");
        }
    
        public virtual int SP_MATERIAL_CAPACITACION_DELETE(Nullable<int> codigoMaterial)
        {
            var codigoMaterialParameter = codigoMaterial.HasValue ?
                new ObjectParameter("codigoMaterial", codigoMaterial) :
                new ObjectParameter("codigoMaterial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MATERIAL_CAPACITACION_DELETE", codigoMaterialParameter);
        }
    
        public virtual int SP_PARTICIPANTES_CAPACITACION_DELETE(Nullable<int> codigoCapacitacion, Nullable<int> codigoDocente)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            var codigoDocenteParameter = codigoDocente.HasValue ?
                new ObjectParameter("codigoDocente", codigoDocente) :
                new ObjectParameter("codigoDocente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PARTICIPANTES_CAPACITACION_DELETE", codigoCapacitacionParameter, codigoDocenteParameter);
        }
    
        public virtual int SP_CAPACITACION_UPDATE(Nullable<int> codCapacitacion, string nombre, Nullable<int> codigoPeriodo, string descripcion, string correoContacto, Nullable<bool> enviarNotificacion, Nullable<int> periodicidadEnvio, Nullable<bool> capacitacionActiva, Nullable<System.DateTime> fechaCreacion, Nullable<System.DateTime> fechaModificacióm, string usuarioCreacion, string usuarioModificacion)
        {
            var codCapacitacionParameter = codCapacitacion.HasValue ?
                new ObjectParameter("codCapacitacion", codCapacitacion) :
                new ObjectParameter("codCapacitacion", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var codigoPeriodoParameter = codigoPeriodo.HasValue ?
                new ObjectParameter("codigoPeriodo", codigoPeriodo) :
                new ObjectParameter("codigoPeriodo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var correoContactoParameter = correoContacto != null ?
                new ObjectParameter("correoContacto", correoContacto) :
                new ObjectParameter("correoContacto", typeof(string));
    
            var enviarNotificacionParameter = enviarNotificacion.HasValue ?
                new ObjectParameter("enviarNotificacion", enviarNotificacion) :
                new ObjectParameter("enviarNotificacion", typeof(bool));
    
            var periodicidadEnvioParameter = periodicidadEnvio.HasValue ?
                new ObjectParameter("periodicidadEnvio", periodicidadEnvio) :
                new ObjectParameter("periodicidadEnvio", typeof(int));
    
            var capacitacionActivaParameter = capacitacionActiva.HasValue ?
                new ObjectParameter("capacitacionActiva", capacitacionActiva) :
                new ObjectParameter("capacitacionActiva", typeof(bool));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("fechaCreacion", fechaCreacion) :
                new ObjectParameter("fechaCreacion", typeof(System.DateTime));
    
            var fechaModificaciómParameter = fechaModificacióm.HasValue ?
                new ObjectParameter("fechaModificacióm", fechaModificacióm) :
                new ObjectParameter("fechaModificacióm", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPACITACION_UPDATE", codCapacitacionParameter, nombreParameter, codigoPeriodoParameter, descripcionParameter, correoContactoParameter, enviarNotificacionParameter, periodicidadEnvioParameter, capacitacionActivaParameter, fechaCreacionParameter, fechaModificaciómParameter, usuarioCreacionParameter, usuarioModificacionParameter);
        }
    
        public virtual ObjectResult<SP_ACTIVIDAD_RETRIEVE_BY_CURSO3_Result> SP_ACTIVIDAD_RETRIEVE_BY_CURSO3(Nullable<int> idperiodo, string estado)
        {
            var idperiodoParameter = idperiodo.HasValue ?
                new ObjectParameter("idperiodo", idperiodo) :
                new ObjectParameter("idperiodo", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTIVIDAD_RETRIEVE_BY_CURSO3_Result>("SP_ACTIVIDAD_RETRIEVE_BY_CURSO3", idperiodoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<SP_PERIODO_RETRIEVE_Result> SP_PERIODO_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PERIODO_RETRIEVE_Result>("SP_PERIODO_RETRIEVE");
        }
    
        public virtual ObjectResult<SP_SEMANA_RETRIEVE_Result> SP_SEMANA_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEMANA_RETRIEVE_Result>("SP_SEMANA_RETRIEVE");
        }
    
        public virtual ObjectResult<SP_UNIDAD_RETRIEVE_Result> SP_UNIDAD_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UNIDAD_RETRIEVE_Result>("SP_UNIDAD_RETRIEVE");
        }
    
        public virtual ObjectResult<SP_TALLER_RETRIEVE_BY_CAPACITACION_Result> SP_TALLER_RETRIEVE_BY_CAPACITACION(Nullable<int> codigoCapacitacion)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TALLER_RETRIEVE_BY_CAPACITACION_Result>("SP_TALLER_RETRIEVE_BY_CAPACITACION", codigoCapacitacionParameter);
        }
    
        public virtual ObjectResult<SP_AULA_RETRIEVE_Result> SP_AULA_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AULA_RETRIEVE_Result>("SP_AULA_RETRIEVE");
        }
    
        public virtual ObjectResult<SP_SEDE_RETRIEVE_Result> SP_SEDE_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEDE_RETRIEVE_Result>("SP_SEDE_RETRIEVE");
        }
    
        public virtual int SP_DETALLE_CAPACITACION_CREATE(Nullable<int> codCapacitacion, Nullable<int> codTaller, string codAulaVirtual, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codSede, string lugar, Nullable<decimal> sesionesPresenciales, Nullable<decimal> sesionesVirtuales, Nullable<System.DateTime> fechaEnvioNotificacion)
        {
            var codCapacitacionParameter = codCapacitacion.HasValue ?
                new ObjectParameter("codCapacitacion", codCapacitacion) :
                new ObjectParameter("codCapacitacion", typeof(int));
    
            var codTallerParameter = codTaller.HasValue ?
                new ObjectParameter("codTaller", codTaller) :
                new ObjectParameter("codTaller", typeof(int));
    
            var codAulaVirtualParameter = codAulaVirtual != null ?
                new ObjectParameter("codAulaVirtual", codAulaVirtual) :
                new ObjectParameter("codAulaVirtual", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var codSedeParameter = codSede.HasValue ?
                new ObjectParameter("codSede", codSede) :
                new ObjectParameter("codSede", typeof(int));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("lugar", lugar) :
                new ObjectParameter("lugar", typeof(string));
    
            var sesionesPresencialesParameter = sesionesPresenciales.HasValue ?
                new ObjectParameter("sesionesPresenciales", sesionesPresenciales) :
                new ObjectParameter("sesionesPresenciales", typeof(decimal));
    
            var sesionesVirtualesParameter = sesionesVirtuales.HasValue ?
                new ObjectParameter("sesionesVirtuales", sesionesVirtuales) :
                new ObjectParameter("sesionesVirtuales", typeof(decimal));
    
            var fechaEnvioNotificacionParameter = fechaEnvioNotificacion.HasValue ?
                new ObjectParameter("fechaEnvioNotificacion", fechaEnvioNotificacion) :
                new ObjectParameter("fechaEnvioNotificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DETALLE_CAPACITACION_CREATE", codCapacitacionParameter, codTallerParameter, codAulaVirtualParameter, fechaInicioParameter, fechaFinParameter, codSedeParameter, lugarParameter, sesionesPresencialesParameter, sesionesVirtualesParameter, fechaEnvioNotificacionParameter);
        }
    
        public virtual int SP_DETALLECAPACITACION_UPDATE(Nullable<int> codDetalleCapacitacion, Nullable<int> codCapacitacion, Nullable<int> codTaller, string codAulaVirtual, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codSede, string lugar, Nullable<decimal> sesionesPresenciales, Nullable<decimal> sesionesVirtuales, Nullable<System.DateTime> fechaEnvioNotificacion, Nullable<System.DateTime> fechaCreacion)
        {
            var codDetalleCapacitacionParameter = codDetalleCapacitacion.HasValue ?
                new ObjectParameter("codDetalleCapacitacion", codDetalleCapacitacion) :
                new ObjectParameter("codDetalleCapacitacion", typeof(int));
    
            var codCapacitacionParameter = codCapacitacion.HasValue ?
                new ObjectParameter("codCapacitacion", codCapacitacion) :
                new ObjectParameter("codCapacitacion", typeof(int));
    
            var codTallerParameter = codTaller.HasValue ?
                new ObjectParameter("codTaller", codTaller) :
                new ObjectParameter("codTaller", typeof(int));
    
            var codAulaVirtualParameter = codAulaVirtual != null ?
                new ObjectParameter("codAulaVirtual", codAulaVirtual) :
                new ObjectParameter("codAulaVirtual", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var codSedeParameter = codSede.HasValue ?
                new ObjectParameter("codSede", codSede) :
                new ObjectParameter("codSede", typeof(int));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("lugar", lugar) :
                new ObjectParameter("lugar", typeof(string));
    
            var sesionesPresencialesParameter = sesionesPresenciales.HasValue ?
                new ObjectParameter("sesionesPresenciales", sesionesPresenciales) :
                new ObjectParameter("sesionesPresenciales", typeof(decimal));
    
            var sesionesVirtualesParameter = sesionesVirtuales.HasValue ?
                new ObjectParameter("sesionesVirtuales", sesionesVirtuales) :
                new ObjectParameter("sesionesVirtuales", typeof(decimal));
    
            var fechaEnvioNotificacionParameter = fechaEnvioNotificacion.HasValue ?
                new ObjectParameter("fechaEnvioNotificacion", fechaEnvioNotificacion) :
                new ObjectParameter("fechaEnvioNotificacion", typeof(System.DateTime));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("fechaCreacion", fechaCreacion) :
                new ObjectParameter("fechaCreacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DETALLECAPACITACION_UPDATE", codDetalleCapacitacionParameter, codCapacitacionParameter, codTallerParameter, codAulaVirtualParameter, fechaInicioParameter, fechaFinParameter, codSedeParameter, lugarParameter, sesionesPresencialesParameter, sesionesVirtualesParameter, fechaEnvioNotificacionParameter, fechaCreacionParameter);
        }
    
        public virtual ObjectResult<SP_DETALLECAPACITACION_RETRIEVE_Result> SP_DETALLECAPACITACION_RETRIEVE(Nullable<int> codDetalleCapacitacion)
        {
            var codDetalleCapacitacionParameter = codDetalleCapacitacion.HasValue ?
                new ObjectParameter("codDetalleCapacitacion", codDetalleCapacitacion) :
                new ObjectParameter("codDetalleCapacitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DETALLECAPACITACION_RETRIEVE_Result>("SP_DETALLECAPACITACION_RETRIEVE", codDetalleCapacitacionParameter);
        }
    
        public virtual ObjectResult<SP_CURSO_LOAD_Result> SP_CURSO_LOAD(Nullable<int> coDireccion)
        {
            var coDireccionParameter = coDireccion.HasValue ?
                new ObjectParameter("coDireccion", coDireccion) :
                new ObjectParameter("coDireccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CURSO_LOAD_Result>("SP_CURSO_LOAD", coDireccionParameter);
        }
    
        public virtual ObjectResult<SP_DIRECCION_LOAD_Result> SP_DIRECCION_LOAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DIRECCION_LOAD_Result>("SP_DIRECCION_LOAD");
        }
    
        public virtual ObjectResult<SP_FOCUSGROUP_RETRIEVE_BY_CURSO_ESTADO_Result> SP_FOCUSGROUP_RETRIEVE_BY_CURSO_ESTADO(Nullable<int> codCurso, string estado)
        {
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FOCUSGROUP_RETRIEVE_BY_CURSO_ESTADO_Result>("SP_FOCUSGROUP_RETRIEVE_BY_CURSO_ESTADO", codCursoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<SP_FOCUSGROUP_RETRIEVE_BY_CURSO_Result> SP_FOCUSGROUP_RETRIEVE_BY_CURSO(Nullable<int> codCurso)
        {
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FOCUSGROUP_RETRIEVE_BY_CURSO_Result>("SP_FOCUSGROUP_RETRIEVE_BY_CURSO", codCursoParameter);
        }
    
        public virtual ObjectResult<SP_MODALIDAD_LOAD_Result> SP_MODALIDAD_LOAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MODALIDAD_LOAD_Result>("SP_MODALIDAD_LOAD");
        }
    
        public virtual ObjectResult<SP_TIPORECURSO_LOAD_Result> SP_TIPORECURSO_LOAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TIPORECURSO_LOAD_Result>("SP_TIPORECURSO_LOAD");
        }
    
        public virtual ObjectResult<SP_TAREAS_RETRIEVE_BY_ACTAS_Result> SP_TAREAS_RETRIEVE_BY_ACTAS(Nullable<int> codModalidad, string estadoTarea, Nullable<int> estadoActa)
        {
            var codModalidadParameter = codModalidad.HasValue ?
                new ObjectParameter("codModalidad", codModalidad) :
                new ObjectParameter("codModalidad", typeof(int));
    
            var estadoTareaParameter = estadoTarea != null ?
                new ObjectParameter("estadoTarea", estadoTarea) :
                new ObjectParameter("estadoTarea", typeof(string));
    
            var estadoActaParameter = estadoActa.HasValue ?
                new ObjectParameter("estadoActa", estadoActa) :
                new ObjectParameter("estadoActa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TAREAS_RETRIEVE_BY_ACTAS_Result>("SP_TAREAS_RETRIEVE_BY_ACTAS", codModalidadParameter, estadoTareaParameter, estadoActaParameter);
        }
    
        public virtual ObjectResult<SP_DOCENTE_RETRIEVE_BY_DIRECCION_Result> SP_DOCENTE_RETRIEVE_BY_DIRECCION(Nullable<int> codDireccion)
        {
            var codDireccionParameter = codDireccion.HasValue ?
                new ObjectParameter("codDireccion", codDireccion) :
                new ObjectParameter("codDireccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOCENTE_RETRIEVE_BY_DIRECCION_Result>("SP_DOCENTE_RETRIEVE_BY_DIRECCION", codDireccionParameter);
        }
    
        public virtual ObjectResult<SP_TIEMPO_RETRIEVE_Result> SP_TIEMPO_RETRIEVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TIEMPO_RETRIEVE_Result>("SP_TIEMPO_RETRIEVE");
        }
    
        public virtual ObjectResult<SP_HORARIO_RETRIEVE_BY_CURSO_PERIODO_MODALIDAD_DOCENTE_Result> SP_HORARIO_RETRIEVE_BY_CURSO_PERIODO_MODALIDAD_DOCENTE(Nullable<int> codCurso, Nullable<int> codModalidad, string semana, Nullable<int> codDocente)
        {
            var codCursoParameter = codCurso.HasValue ?
                new ObjectParameter("codCurso", codCurso) :
                new ObjectParameter("codCurso", typeof(int));
    
            var codModalidadParameter = codModalidad.HasValue ?
                new ObjectParameter("codModalidad", codModalidad) :
                new ObjectParameter("codModalidad", typeof(int));
    
            var semanaParameter = semana != null ?
                new ObjectParameter("semana", semana) :
                new ObjectParameter("semana", typeof(string));
    
            var codDocenteParameter = codDocente.HasValue ?
                new ObjectParameter("codDocente", codDocente) :
                new ObjectParameter("codDocente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HORARIO_RETRIEVE_BY_CURSO_PERIODO_MODALIDAD_DOCENTE_Result>("SP_HORARIO_RETRIEVE_BY_CURSO_PERIODO_MODALIDAD_DOCENTE", codCursoParameter, codModalidadParameter, semanaParameter, codDocenteParameter);
        }
    }
}
